# Override any defaults specified by `${FOO:-bar}` in `.env` with `FOO=qux`.
# ${VARIABLE:-default} evaluates to default if VARIABLE is unset or empty in the environment.
# ${VARIABLE-default} evaluates to default only if VARIABLE is unset in the environment.

services:
  #                             _                     _
  #   _ __ ___   _____   __    | |__   ___   ___  ___| |_
  #  | '_ ` _ \ / _ \ \ / /____| '_ \ / _ \ / _ \/ __| __|
  #  | | | | | |  __/\ V /_____| |_) | (_) | (_) \__ \ |_
  #  |_| |_| |_|\___| \_/      |_.__/ \___/ \___/|___/\__|
  mev-mevboost:
    profiles: [mev-mevboost]
    image: flashbots/mev-boost:${MEV_MEVBOOST_VERSION:-1.9}
    command: |
      -${NETWORK}
      -loglevel=debug
      -addr=0.0.0.0:18550
      -relay-check
      -relays=${MEV_RELAYS}
      -request-timeout-getheader=${MEV_TIMEOUT_GETHEADER:-950}
      -request-timeout-getpayload=${MEV_TIMEOUT_GETPAYLOAD:-4000}
      -request-timeout-regval=${MEV_TIMEOUT_REGVAL:-3000}
    labels:
      - "promtail-monitored=${MEV_MEV_BOOST_PROMTAIL_MONITORED:-true}"
    networks: [dvnode]
    restart: unless-stopped
