# Override any defaults specified by `${FOO:-bar}` in `.env` with `FOO=qux`.
# ${VARIABLE:-default} evaluates to default if VARIABLE is unset or empty in the environment.
# ${VARIABLE-default} evaluates to default only if VARIABLE is unset in the environment.

services:
  #                            _ _            
  #   __ _ _ __ __ _ _ __   __| (_)_ __   ___ 
  #  / _` | '__/ _` | '_ \ / _` | | '_ \ / _ \
  # | (_| | | | (_| | | | | (_| | | | | |  __/
  #  \__, |_|  \__,_|_| |_|\__,_|_|_| |_|\___|
  #  |___/                  

  beacon:
    profiles: [cl_grandine]
    image: sifrai/grandine:${GRANDINE_VERSION:-1.1.1}
    restart: unless-stopped
    command:
      - --datadir=/root/.grandine
      - --eth1-rpc-urls=http://execution:8551
      - --jwt-secret=/jwt
      - --http-address=0.0.0.0
      - --http-port=5052
      - --network=${NETWORK}
      - --metrics
      - --metrics-port=5054
      - --metrics-address=0.0.0.0
      - --checkpoint-sync-url=${LIGHTHOUSE_CHECKPOINT_SYNC_URL}
      - --builder=http://mev:18550
    ports:
      - 9000:9000     # TCP + UDP LibP2P
    volumes:
      - ./data/grandine:/root/.grandine
      - ./jwt:/jwt:ro
    networks:
      - dvnode