version: "3.8"

# Override any defaults specified by `${FOO:-bar}` in `.env` with `FOO=qux`.
# ${VARIABLE:-default} evaluates to default if VARIABLE is unset or empty in the environment.
# ${VARIABLE-default} evaluates to default only if VARIABLE is unset in the environment.

services:
  #             _   _                         _           _
  #  _ __   ___| |_| |__   ___ _ __ _ __ ___ (_)_ __   __| |
  # | '_ \ / _ \ __| '_ \ / _ \ '__| '_ ` _ \| | '_ \ / _` |
  # | | | |  __/ |_| | | |  __/ |  | | | | | | | | | | (_| |
  # |_| |_|\___|\__|_| |_|\___|_|  |_| |_| |_|_|_| |_|\__,_|
  nethermind:
    image: nethermind/nethermind:${NETHERMIND_VERSION:-1.25.4}
    restart: unless-stopped
    ports:
      - ${NETHERMIND_PORT_P2P:-30303}:30303/tcp # P2P TCP
      - ${NETHERMIND_PORT_P2P:-30303}:30303/udp # P2P UDP
      - ${NETHERMIND_IP_HTTP:-127.0.0.1}:${NETHERMIND_PORT_HTTP:-8545}:8545 # JSON-RPC
      - ${NETHERMIND_IP_ENGINE:-127.0.0.1}:${NETHERMIND_PORT_ENGINE:-8551}:8551 # ENGINE-API
    command: |
      --config=${NETWORK:-holesky}
      --datadir=data
      --HealthChecks.Enabled=true
      --JsonRpc.Enabled=true
      --JsonRpc.JwtSecretFile="/root/jwt/jwt.hex"
      --JsonRpc.EngineHost=0.0.0.0
      --JsonRpc.EnginePort=8551
      --JsonRpc.Host=0.0.0.0
      --JsonRpc.Port=8545
      --Sync.SnapSync=true
      --Sync.AncientBodiesBarrier=4367322
      --Sync.AncientReceiptsBarrier=4367322
    networks: [dvnode]
    volumes:
      - ./data/nethermind:/nethermind/data
      - ./jwt:/root/jwt

  #  _ _       _     _   _
  # | (_) __ _| |__ | |_| |__   ___  _   _ ___  ___
  # | | |/ _` | '_ \| __| '_ \ / _ \| | | / __|/ _ \
  # | | | (_| | | | | |_| | | | (_) | |_| \__ \  __/
  # |_|_|\__, |_| |_|\__|_| |_|\___/ \__,_|___/\___|
  #      |___/

  lighthouse:
    image: sigp/lighthouse:${LIGHTHOUSE_VERSION:-v5.0.0}
    ports:
      - ${LIGHTHOUSE_PORT_P2P:-9000}:9000/tcp # P2P TCP
      - ${LIGHTHOUSE_PORT_P2P:-9000}:9000/udp # P2P UDP
    command: |
      lighthouse bn
      --network=${NETWORK:-holesky}
      --checkpoint-sync-url=${LIGHTHOUSE_CHECKPOINT_SYNC_URL:-https://mainnet.checkpoint.sigp.io/}
      --execution-endpoint=http://nethermind:8551
      --execution-jwt=/opt/jwt/jwt.hex
      --datadir=/opt/app/beacon/
      --builder=http://mev-boost:18550
      --http
      --http-address=0.0.0.0
      --http-port=5052
      --metrics
      --metrics-address=0.0.0.0
      --metrics-port=5054
      --metrics-allow-origin="*"
    networks: [dvnode]
    volumes:
      - ./data/lighthouse:/opt/app/beacon
      - ./jwt:/opt/jwt
    restart: unless-stopped

  #       _
  #   ___| |__   __ _ _ __ ___  _ __
  #  / __| '_ \ / _` | '__/ _ \| '_ \
  # | (__| | | | (_| | | | (_) | | | |
  #  \___|_| |_|\__,_|_|  \___/|_| |_|

  charon:
    image: obolnetwork/charon:${CHARON_VERSION:-v0.19.1}
    environment:
      - CHARON_BEACON_NODE_ENDPOINTS=${CHARON_BEACON_NODE_ENDPOINTS:-http://lighthouse:5052}
      - CHARON_LOG_LEVEL=${CHARON_LOG_LEVEL:-debug}
      - CHARON_LOG_FORMAT=${CHARON_LOG_FORMAT:-console}
      - CHARON_P2P_RELAYS=${CHARON_P2P_RELAYS:-https://0.relay.obol.tech,https://1.relay.obol.tech/}
      - CHARON_P2P_EXTERNAL_HOSTNAME=${CHARON_P2P_EXTERNAL_HOSTNAME:-} # Empty default required to avoid warnings.
      - CHARON_P2P_TCP_ADDRESS=0.0.0.0:${CHARON_PORT_P2P_TCP:-3610}
      - CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600
      - CHARON_MONITORING_ADDRESS=0.0.0.0:3620
      - CHARON_BUILDER_API=${BUILDER_API_ENABLED:-true}
      - CHARON_FEATURE_SET_ENABLE=eager_double_linear,consensus_participate
      - CHARON_LOKI_ADDRESSES=${CHARON_LOKI_ADDRESSES:-http://loki:3100/loki/api/v1/push}
      - CHARON_LOKI_SERVICE=charon
    ports:
      - ${CHARON_PORT_P2P_TCP:-3610}:${CHARON_PORT_P2P_TCP:-3610}/tcp # P2P TCP libp2p
    networks: [dvnode]
    volumes:
      - .charon:/opt/charon/.charon
    restart: unless-stopped
    healthcheck:
      test: wget -qO- http://localhost:3620/readyz

  #  _           _           _
  # | | ___   __| | ___  ___| |_ __ _ _ __
  # | |/ _ \ / _` |/ _ \/ __| __/ _` | '__|
  # | | (_) | (_| |  __/\__ \ || (_| | |
  # |_|\___/ \__,_|\___||___/\__\__,_|_|

  lodestar:
    image: chainsafe/lodestar:${LODESTAR_VERSION:-v1.16.0}
    depends_on: [charon]
    entrypoint: /opt/lodestar/run.sh
    networks: [dvnode]
    environment:
      BEACON_NODE_ADDRESS: http://charon:3600
      NETWORK: ${NETWORK:-holesky}
      BUILDER_API_ENABLED: ${BUILDER_API_ENABLED:-true}
      BUILDER_SELECTION: ${BUILDER_SELECTION:-builderonly}
    volumes:
      - ./lodestar/run.sh:/opt/lodestar/run.sh
      - .charon/validator_keys:/home/charon/validator_keys
      - ./data/lodestar:/opt/data
    restart: unless-stopped

  #      _                     _
  #  _ __ ___   _____   __    | |__   ___   ___  ___| |_
  #  | '_ ` _ \ / _ \ \ / /____| '_ \ / _ \ / _ \/ __| __|
  #  | | | | | |  __/\ V /_____| |_) | (_) | (_) \__ \ |_
  #  |_| |_| |_|\___| \_/      |_.__/ \___/ \___/|___/\__|
  mev-boost:
    image: flashbots/mev-boost:${MEVBOOST_VERSION:-1.7}
    command: |
      -${NETWORK:-holesky}
      -loglevel=debug
      -addr=0.0.0.0:18550
      -relay-check
      -relays=${MEVBOOST_RELAYS:-"https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@boost-relay-holesky.flashbots.net,https://0xb1d229d9c21298a87846c7022ebeef277dfc321fe674fa45312e20b5b6c400bfde9383f801848d7837ed5fc449083a12@relay-holesky.edennetwork.io,https://0xaa58208899c6105603b74396734a6263cc7d947f444f396a90f7b7d3e65d102aec7e5e5291b27e08d02c50a050825c2f@holesky.titanrelay.xyz,https://0x821f2a65afb70e7f2e820a925a9b4c80a159620582c1766b1b09729fec178b11ea22abb3a51f07b288be815a1a2ff516@bloxroute.holesky.blxrbdn.com"}
    networks: [dvnode]
    restart: unless-stopped

  #                        _ _             _
  #  _ __ ___   ___  _ __ (_) |_ ___  _ __(_)_ __   __ _
  # | '_ ` _ \ / _ \| '_ \| | __/ _ \| '__| | '_ \ / _` |
  # | | | | | | (_) | | | | | || (_) | |  | | | | | (_| |
  # |_| |_| |_|\___/|_| |_|_|\__\___/|_|  |_|_| |_|\__, |
  #                                                |___/

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-v2.46.0}
    user: ":"
    networks: [dvnode]
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-10.3.1}
    user: ":"
    ports:
      - ${MONITORING_IP_GRAFANA:-127.0.0.1}:${MONITORING_PORT_GRAFANA:-3000}:3000
    networks: [dvnode]
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/datasource.yml
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/dashboards:/etc/dashboards
      - ./data/grafana:/var/lib/grafana
    restart: unless-stopped

  loki:
    image: grafana/loki:${LOKI_VERSION:-2.8.2}
    user: ":"
    networks: [dvnode]
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml
      - ./data/loki:/opt/loki
    restart: unless-stopped

  #             _ _     _       _                        _           _
  # __   ____ _| (_) __| | __ _| |_ ___  _ __       ___ (_) ___  ___| |_ ___  _ __
  # \ \ / / _` | | |/ _` |/ _` | __/ _ \| '__|____ / _ \| |/ _ \/ __| __/ _ \| '__|
  #  \ V / (_| | | | (_| | (_| | || (_) | | |_____|  __/| |  __/ (__| || (_) | |
  #   \_/ \__,_|_|_|\__,_|\__,_|\__\___/|_|        \___|/ |\___|\___|\__\___/|_|
  #                                                   |__/

  validator-ejector:
    image: lidofinance/validator-ejector:${VALIDATOR_EJECTOR_VERSION:-1.3.0}
    user: ":"
    networks: [dvnode]
    volumes:
      - ./validator-ejector:/exitmessages
    restart: unless-stopped
    environment:
      - EXECUTION_NODE=${VE_EXECUTION_NODE_URL:-http://nethermind:8545}
      - CONSENSUS_NODE=${VE_BEACON_NODE_URL:-http://lighthouse:5052}
      - LOCATOR_ADDRESS=${VE_LOCATOR_ADDRESS:-0x28FAB2059C713A7F9D8c86Db49f9bb0e96Af1ef8}
      - STAKING_MODULE_ID=${VE_STAKING_MODULE_ID:-2}
      - OPERATOR_ID=${VE_OPERATOR_ID}
      - ORACLE_ADDRESSES_ALLOWLIST=${VE_ORACLE_ADDRESSES_ALLOWLIST:-["0x12A1D74F8697b9f4F1eEBb0a9d0FB6a751366399","0xD892c09b556b547c80B7d8c8cB8d75bf541B2284","0xf7aE520e99ed3C41180B5E12681d31Aa7302E4e5"]}
      - MESSAGES_LOCATION=/exitmessages
      - RUN_METRICS=true
      - HTTP_PORT=8989
      - DISABLE_SECURITY_DONT_USE_IN_PRODUCTION=${DISABLE_EJECTOR_SECURITY:-false}

  #  _ _     _                 _                      _ _
  # | (_) __| | ___         __| |_   __      _____  _(_) |_
  # | | |/ _` |/ _ \ _____ / _` \ \ / /____ / _ \ \/ / | __|
  # | | | (_| | (_) |_____| (_| |\ V /_____|  __/>  <| | |_
  # |_|_|\__,_|\___/       \__,_| \_/       \___/_/\_\_|\__|
  #

  lido-dv-exit:
    image: obolnetwork/lido-dv-exit:${LIDO_DV_EXIT_VERSION:-e8bee1f}
    user: ":"
    networks: [dvnode]
    volumes:
      - ./validator-ejector:/exitmessages
      - .charon:/charon
    environment:
      - LIDODVEXIT_BEACON_NODE_URL=${LIDO_DV_EXIT_BEACON_NODE_URL:-http://lighthouse:5052}
      - LIDODVEXIT_CHARON_RUNTIME_DIR=/charon
      - LIDODVEXIT_EJECTOR_EXIT_PATH=/exitmessages
      - LIDODVEXIT_EXIT_EPOCH=${LIDODVEXIT_EXIT_EPOCH:-256}
      - LIDODVEXIT_LOG_LEVEL=${LIDO_DV_EXIT_LOG_LEVEL:-info}
      - LIDODVEXIT_VALIDATOR_QUERY_CHUNK_SIZE=${LIDO_DV_EXIT_VALIDATOR_QUERY_CHUNK_SIZE:-5}
    restart: on-failure

networks:
  dvnode:
