# Override any defaults specified by `${FOO:-bar}` in `.env` with `FOO=qux`.
# ${VARIABLE:-default} evaluates to default if VARIABLE is unset or empty in the environment.
# ${VARIABLE-default} evaluates to default only if VARIABLE is unset in the environment.

services:
  #       _
  #   ___| |__   __ _ _ __ ___  _ __
  #  / __| '_ \ / _` | '__/ _ \| '_ \
  # | (__| | | | (_| | | | (_) | | | |
  #  \___|_| |_|\__,_|_|  \___/|_| |_|

  charon:
    image: obolnetwork/charon:${CHARON_VERSION:-v1.5.2}
    environment:
      - CHARON_BEACON_NODE_ENDPOINTS=${CHARON_BEACON_NODE_ENDPOINTS:-http://cl-${CL}:5052}
      - CHARON_BEACON_NODE_HEADERS=${CHARON_BEACON_NODE_HEADERS:-}
      - CHARON_BEACON_NODE_TIMEOUT=${CHARON_BEACON_NODE_TIMEOUT:-3s}
      - CHARON_BEACON_NODE_SUBMIT_TIMEOUT=${CHARON_BEACON_NODE_SUBMIT_TIMEOUT:-4s}
      - CHARON_FALLBACK_BEACON_NODE_ENDPOINTS=${CHARON_FALLBACK_BEACON_NODE_ENDPOINTS:-}
      - CHARON_LOG_LEVEL=${CHARON_LOG_LEVEL:-debug}
      - CHARON_LOG_FORMAT=${CHARON_LOG_FORMAT:-console}
      - CHARON_P2P_RELAYS=${CHARON_P2P_RELAYS:-https://0.relay.obol.tech,https://1.relay.obol.tech/}
      - CHARON_P2P_EXTERNAL_HOSTNAME=${CHARON_P2P_EXTERNAL_HOSTNAME:-} # Empty default required to avoid warnings.
      - CHARON_P2P_TCP_ADDRESS=0.0.0.0:${CHARON_PORT_P2P_TCP:-3610}
      - CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600
      - CHARON_MONITORING_ADDRESS=0.0.0.0:3620
      - CHARON_BUILDER_API=${BUILDER_API_ENABLED:-true}
      - CHARON_FEATURE_SET_ENABLE=eager_double_linear,consensus_participate
      - CHARON_LOKI_ADDRESSES=${CHARON_LOKI_ADDRESSES:-http://loki:3100/loki/api/v1/push}
      - CHARON_LOKI_SERVICE=charon
      - CHARON_NICKNAME=${CHARON_NICKNAME:-}
      - CHARON_EXECUTION_CLIENT_RPC_ENDPOINT=${CHARON_EXECUTION_CLIENT_RPC_ENDPOINT:-http://nethermind:8545}
    ports:
      - ${CHARON_PORT_P2P_TCP:-3610}:${CHARON_PORT_P2P_TCP:-3610}/tcp # P2P TCP libp2p
    networks: [dvnode]
    labels:
      - "promtail-monitored=${CHARON_PROMTAIL_MONITORED:-true}"
    volumes:
      - .charon:/opt/charon/.charon
    restart: unless-stopped
    healthcheck:
      test: wget -qO- http://localhost:3620/readyz

  #                        _ _             _
  #  _ __ ___   ___  _ __ (_) |_ ___  _ __(_)_ __   __ _
  # | '_ ` _ \ / _ \| '_ \| | __/ _ \| '__| | '_ \ / _` |
  # | | | | | | (_) | | | | | || (_) | |  | | | | | (_| |
  # |_| |_| |_|\___/|_| |_|_|\__\___/|_|  |_|_| |_|\__, |
  #                                                |___/

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-v2.53.5}
    user: ":"
    networks: [dvnode]
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-10.4.0}
    user: ":"
    ports:
      - ${MONITORING_IP_GRAFANA:-0.0.0.0}:${MONITORING_PORT_GRAFANA:-3000}:3000
    networks: [dvnode]
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/datasource.yml
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/dashboards:/etc/dashboards
      - ./data/grafana:/var/lib/grafana
    restart: unless-stopped

  loki:
    image: grafana/loki:${LOKI_VERSION:-2.9.15}
    user: ":"
    networks: [dvnode]
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml
      - ./data/loki:/opt/loki
    restart: unless-stopped

  #             _ _     _       _                        _           _
  # __   ____ _| (_) __| | __ _| |_ ___  _ __       ___ (_) ___  ___| |_ ___  _ __
  # \ \ / / _` | | |/ _` |/ _` | __/ _ \| '__|____ / _ \| |/ _ \/ __| __/ _ \| '__|
  #  \ V / (_| | | | (_| | (_| | || (_) | | |_____|  __/| |  __/ (__| || (_) | |
  #   \_/ \__,_|_|_|\__,_|\__,_|\__\___/|_|        \___|/ |\___|\___|\__\___/|_|
  #                                                   |__/

  # validator-ejector:
  #   image: lidofinance/validator-ejector:${VALIDATOR_EJECTOR_VERSION:-1.7.0}
  #   user: ":"
  #   networks: [dvnode]
  #   volumes:
  #     - ./validator-ejector:/exitmessages
  #   labels:
  #     - "promtail-monitored=${EJECTOR_PROMTAIL_MONITORED:-true}"
  #   restart: unless-stopped
  #   environment:
  #     - EXECUTION_NODE=${VE_EXECUTION_NODE_URL:-http://nethermind:8545}
  #     - CONSENSUS_NODE=${VE_BEACON_NODE_URL:-http://lighthouse:5052}
  #     - LOCATOR_ADDRESS=${VE_LOCATOR_ADDRESS}
  #     - STAKING_MODULE_ID=${VE_STAKING_MODULE_ID:-2}
  #     - OPERATOR_ID=${VE_OPERATOR_ID}
  #     - ORACLE_ADDRESSES_ALLOWLIST=${VE_ORACLE_ADDRESSES_ALLOWLIST}
  #     - MESSAGES_LOCATION=/exitmessages
  #     - RUN_METRICS=true
  #     - HTTP_PORT=8989
  #     - DISABLE_SECURITY_DONT_USE_IN_PRODUCTION=${DISABLE_EJECTOR_SECURITY:-false}

  #  _ _     _                 _                      _ _
  # | (_) __| | ___         __| |_   __      _____  _(_) |_
  # | | |/ _` |/ _ \ _____ / _` \ \ / /____ / _ \ \/ / | __|
  # | | | (_| | (_) |_____| (_| |\ V /_____|  __/>  <| | |_
  # |_|_|\__,_|\___/       \__,_| \_/       \___/_/\_\_|\__|
  #

  lido-dv-exit:
    image: obolnetwork/lido-dv-exit:${LIDO_DV_EXIT_VERSION:-v0.3.0}
    user: ":"
    networks: [dvnode]
    volumes:
      - ./validator-ejector:/exitmessages
      - .charon:/charon
    labels:
      - "promtail-monitored=${DV_EXIT_PROMTAIL_MONITORED:-true}"
    environment:
      - LIDODVEXIT_BEACON_NODE_URL=${LIDO_DV_EXIT_BEACON_NODE_URL:-http://lighthouse:5052}
      - LIDODVEXIT_CHARON_RUNTIME_DIR=/charon
      - LIDODVEXIT_EJECTOR_EXIT_PATH=/exitmessages
      - LIDODVEXIT_EXIT_EPOCH=${LIDODVEXIT_EXIT_EPOCH}
      - LIDODVEXIT_LOG_LEVEL=${LIDO_DV_EXIT_LOG_LEVEL:-info}
      - LIDODVEXIT_VALIDATOR_QUERY_CHUNK_SIZE=${LIDO_DV_EXIT_VALIDATOR_QUERY_CHUNK_SIZE:-5}
    restart: unless-stopped

networks:
  dvnode:
